# Generated by Django 3.2.16 on 2023-01-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230111_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='image',
            new_name='logo',
        ),
    ]
