# Generated by Django 3.2.16 on 2023-01-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_image_vendor_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='logo',
            new_name='image',
        ),
    ]
